/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int ACHAVES = 14;
  /** RegularExpression Id. */
  int FCHAVES = 15;
  /** RegularExpression Id. */
  int APARNTS = 16;
  /** RegularExpression Id. */
  int FPARNTS = 17;
  /** RegularExpression Id. */
  int VIRG = 18;
  /** RegularExpression Id. */
  int PTVIRG = 19;
  /** RegularExpression Id. */
  int NUM = 20;
  /** RegularExpression Id. */
  int BOOL = 21;
  /** RegularExpression Id. */
  int TIPO = 22;
  /** RegularExpression Id. */
  int OP = 23;
  /** RegularExpression Id. */
  int ID = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\":=\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\"function\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "<NUM>",
    "<BOOL>",
    "<TIPO>",
    "<OP>",
    "<ID>",
  };

}
